version: '3'
services:
  # db:
  #   image:  mysql:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
  #     - "MYSQL_USER=${DB_USER}"
  #     - "MYSQL_PASSWORD=${DB_PASSWORD}"
  #     - "MYSQL_DATABASE=${DB_NAME}"   
  web:
    build: .
    ports:
      - "1909:1909"
    volumes:
      - ".:/app"
    # depends_on:
    #   - db
    #   - redis
    # links:
    #   - "db:database"   
  # redis:
  #   image: "redis:latest"
  #   ports:
  #     - "6379:6379"
  # localstack:
  #   container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
  #   image: localstack/localstack:latest
  #   ports:
  #     - "127.0.0.1:4566:4566"            # LocalStack Gateway
  #     - "127.0.0.1:4510-4559:4510-4559"  # external services port range
  #   environment:
  #     - DEBUG=${DEBUG-}
  #     - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #   volumes:
  #     - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
